action_id: trunk-cache-prune
date: 2023-04-17 01:01:00
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 127
  out: ""
  err: "trunk-cache-prune: trunk: command not found\n"
timestamp: 1681693260
full_timestamp:
  nanos: 42480000
  seconds: 1681693260
trunk_version: 1.7.0
