action_id: trunk-upgrade-available
date: 2023-04-16 05:53:58
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 127
  out: ""
  err: "trunk-upgrade-available: trunk: command not found\n"
timestamp: 1681624438
full_timestamp:
  nanos: 264280000
  seconds: 1681624438
trunk_version: 1.7.0
