action_id: trunk-upgrade-available
date: 2023-04-16 06:52:24
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 127
  out: ""
  err: "trunk-upgrade-available: trunk: command not found\n"
timestamp: 1681627944
full_timestamp:
  nanos: 208652000
  seconds: 1681627944
trunk_version: 1.7.0
