action_id: trunk-upgrade-available
date: 2023-04-17 01:01:00
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 127
  out: ""
  err: "trunk-upgrade-available: trunk: command not found\n"
timestamp: 1681693260
full_timestamp:
  nanos: 89800000
  seconds: 1681693260
trunk_version: 1.7.0
